# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MemeMe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTVTracker
   pod 'SwiftyBeaver'
  
  #  pod 'Reveal-SDK', :configurations => ['Debug']
end

